CREATE TABLE IF NOT EXISTS payroll_settings (
    id CHAR(36) PRIMARY KEY NOT NULL DEFAULT (UUID()),
    config_name VARCHAR(255) NOT NULL,
    config_key VARCHAR(255) UNIQUE NOT NULL,
    value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)